# DATABASE CONFIG
DATABASE_PATH = "video_generation_analysis.db"

# GENSIM KEYWORD MODEL
GENSIM_MODEL = "glove-wiki-gigaword-50"

# HUGGING FACE KEYWORD MODEL
HUGGING_FACE_MODEL = "mrm8488/t5-base-finetuned-common_gen"

# VIDEO GENERATION CONFIG
GEMINI_API_KEY_ENV = "GEMINI_API_KEY"
GEMINI_MODEL_NAME = "veo-3.1-generate-preview"
VIDEO_DURATION_SECONDS = 8
VIDEO_ASPECT_RATIO = "16:9"
TITLE_MAX_LENGTH = 20
TITLE_MIN_LENGTH = 5
DESCRIPTION_MAX_LENGTH = 150
DESCRIPTION_MIN_LENGTH = 50

# VIDEO UPLOAD CONFIG
YOUTUBE_CLIENT_SECRETS_ENV = "YOUTUBE_CLIENT_SECRETS_FILE"
YOUTUBE_SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]
YOUTUBE_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"
