# DATABASE CONFIG
DATABASE_PATH = "video_generation_analysis.db"

# GENSIM KEYWORD MODEL
GENSIM_MODEL_NAME = "glove-wiki-gigaword-50"

# VIDEO GENERATION CONFIG
GEMINI_API_KEY_ENV = "GEMINI_API_KEY"
GEMINI_MODEL_NAME = "veo-3.1-generate-preview"
VIDEO_DURATION_SECONDS = 8
VIDEO_ASPECT_RATIO = "16:9"
